config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pets#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :pets do
    resources :bookings, only: [:new, :create, :show]
  end

  resources :bookings, only: [:update, :destroy]

  get 'profile', to: 'users#show', as: :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pet
  belongs_to :user

  # validates :booking_date, presence: true
  # validates :booking_location, presence: true

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :pet_details, presence: true
  validates :pet_name, presence: true
  validates :picture_url, presence: true
  # has_many :users, through: :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pets
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: :new

  def show
    @pet = Pet.find(params[:pet_id])
    @booking = @pet.bookings.find(params[:id])

  end

  def new
    @pet = Pet.find(params[:pet_id])
    @booking = Booking.new
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @booking = @pet.bookings.create(booking_params)
    @booking.user = current_user

    if @booking.save
      redirect_to pet_booking_path(@pet, @booking), notice: "Yay! You have successfully booked this pet!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.user == current_user
      @booking.destroy
      redirect_to user_path(current_user)
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:opening_date, :closing_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: :new

  def index
    @pets = Pet.all

    @markers = @pets.geocoded.map do |pet|
      {
        lat: pet.latitude,
        lng: pet.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {pet: pet})
      }
    end
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    if @pet.save
      redirect_to pets_path(@pet), notice: "Your pet has been succesfully added!"
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def pet_params
    params.require(:pet).permit(:pet_name, :pet_details, :picture_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    params[:username]
  end

  def destroy
    sign_out(current_user)
      redirect_to root_path, notice: "You have successfully logged out."
  end

  def show
    @user = current_user
    @pets = current_user.pets
    @bookings = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="simple-form">
  <h1>When would you like to spend some time with <%= @pet.pet_name %>?</h1>
  <%= simple_form_for([@pet, @booking]) do |f| %>
    <div class="input">
      <%= f.input :opening_date,
            as: :string,
            label: "From",
            input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :closing_date,
            as: :string,
            label: "Till",
            input_html: { data: { controller: "datepicker" } } %>
    </div>
    <div class="actions">
      <%= f.submit "Book", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Your booking has been confirmed!</h1>
  <h2><%= @pet.pet_name %></h2>
  <div class="d-flex align-items-center"> <!-- This makes the layout flexible and vertically centered -->
    <div class="col-6">
      <img src="<%= @pet.picture_url %>" alt="Petpic" width="500px">
    </div>
    <div class="col-6">
      <p><strong>Booking date</strong></p>
      <p><strong>From:</strong> <%= @booking.opening_date.strftime("%d-%m-%Y") %></p>
      <p><strong>Till:</strong> <%= @booking.closing_date.strftime("%d-%m-%Y") %></p>
      <%= link_to "My Paw Agenda", user_path(current_user), class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://img.freepik.com/premium-vector/vector-cute-cat-paw-logo-icon-pet-shop-zoo-print-children-textile-grooming-salon-animal-paw_615232-899.jpg?w=740" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://e7.pngegg.com/pngimages/348/800/png-clipart-man-wearing-blue-shirt-illustration-computer-icons-avatar-user-login-avatar-blue-child.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user) , class: "dropdown-item" %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item", data: { turbo: false } %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path %>
          <li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Barriecito&family=Nanum+Gothic&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <div class="layout-style page-container">
      <div class="navbar-container">
        <%= render "layouts/navbar" %>
      </div>
      <div class="content-container">
        <%= yield %>
      </div>
      <div class="footer-container">
        <%= render "layouts/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pets/_form.html.erb
<div class="simple-form">
  <%= simple_form_for(@pet) do |f| %>
    <div class="input">
      <%= f.input :pet_name %>
      <%= f.input :pet_details %>
      <%= f.input :address %>
      <%= f.input :picture_url %>
      <p><%= f.submit "Create Pet", class: "btn btn-secondary" %></p>
    </div>
  <% end %>
</div>

app/views/pets/_formformap.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/pets/_info_window.html.erb
<div>
  <h2>
    <%= link_to pet.pet_name, pet_path(pet), class: "text-decoration-none link-opacity-75-hover no-outline" %>
  </h2>
  <img src="<%= pet.picture_url %>" alt="Petpic" class="center-block img-fluid">
</div>

app/views/pets/index.html.erb
<div class="container">
  <h1 class="title">PETS</h1>
  <h2>Spend some time with one of these cuties</h2>


  <div class="d-flex row">
      <% @pets.each do |pet| %>
      <div class="col-4">
        <%= link_to pet_path(pet), style: "text-decoration: none; color: inherit;" do %>
          <div class="card-product">
            <img src="<%= pet.picture_url %>" alt="Petpic" width="300px">
              <div class="card-product-infos">
                <h2 class= "pet-name"><%= pet.pet_name %></h2>
                <p><%= pet.pet_details %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
<p class="add-pet-button"><%= link_to "Add a Pet", new_pet_path(@pet), class: "btn btn-secondary" %></p>
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/pets/new.html.erb
<h1>Add a new Pet</h1>
<%= render "form" %>

app/views/pets/profile.html.erb
<h1><%= @pet.pet_name %></h1>
<div>
  <img src="<%= @pet.picture_url %>" alt="Petpic" width="300px">
  <p><%= @pet.pet_details %></p>
</div>

<p><%= link_to "Book this Pet", new_pet_booking_path(@pet), class: "btn btn-primary" %>
</p>

app/views/pets/show.html.erb
<div class="page-fix">
<h1>Cute, right?</h1>
  <div class="pet-card">
  <img src="<%= @pet.picture_url %>" alt="Petpic" width="300px">
    <div>
      <h1><%= @pet.pet_name %></h1>
      <p><%= @pet.pet_details %></p>
      <p><%= link_to "Choose me", new_pet_booking_path(@pet), class: "btn btn-secondary" %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" data-bs-toggle="tab" href="#home">My Paw Agenda</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="tab" href="#menu1">My Pets</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="home">
      <h1 class="title">My Paw Agenda</h1>
      <div class="d-flex row">
        <% if @bookings.present? %>
          <% @bookings.each do |booking| %>
            <div class="col-4">
              <div class="card-product position-relative">
                <img src="<%= booking.pet.picture_url %>" alt="Petpic" width="300px">
                <div class="card-product-infos ">
                  <h2 class= "pet-name"><%= booking.pet.pet_name %></h2>
                  <p><%= booking.pet.pet_details %></p>
                  <p><strong>From:</strong> <%= booking.opening_date.strftime("%d-%m-%Y") %></p>
                  <p><strong>Till:</strong> <%= booking.closing_date.strftime("%d-%m-%Y") %></p>
                  <p><%= link_to "Cancel", booking_path(booking),
                    data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'},
                    class: "btn btn-secondary position-absolute bottom-0 end-0 me-2 mb-2" %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="col-6 alert alert-warning position-static">
            <%= link_to "Your booking is empty, go ahead and choose your favorite pet!", root_path , class: "alert-link" %>
          </div>
        <%end%>
      </div>
    </div>
    <div class="tab-pane" id="menu1">
      <h1 class="title">My Pets</h1>
      <div class="d-flex row">
        <% if @pets.present? %>
        <% @pets.each do |pet| %>
          <div class="col-4">
            <%# <%= link_to pet_path(pet), style: "text-decoration: none; color: inherit;" do %>
            <div class="card-product">
              <img src="<%= pet.picture_url %>" alt="Petpic" width="300px">
              <div class="card-product-infos">
                <h2 class= "pet-name"><%= pet.pet_name %></h2>
                <p><%= pet.pet_details %></p>
              </div>
            </div>
          </div>
        <% end %>
        <% else %>
          <div class="col-6 alert alert-warning position-static">
            <%= link_to "You haven't added your pet yet, go ahead and add one!", new_pet_path(@pet) , class: "alert-link" %>
              <a href="#" class="alert-link"></a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>